all:
  hosts:
    rpi: 
      ansible_host: 192.168.2.100
      ansible_user: pi
      ansible_python_interpreter: /usr/bin/python3
  vars:
    server_ip: 192.168.2.100
    docker_network_name: homass

    home_assistant_name: home-assistant
    home_assistant_address: homeassistant.lan
    home_assistant_port: 8123

    pihole_name: pihole
    pihole_address: pihole.lan
    pihole_image: diginc/pi-hole-multiarch:debian_armhf

    proxy_name: proxy

    mqtt_name: mqtt
    mqtt_address: mqtt.lan
