homeassistant:
    name: Home
    latitude: 51.776667
    longitude: 19.454722
    elevation: 200
    unit_system: metric
    time_zone: Europe/Warsaw
    auth_providers:
      - type: trusted_networks
        trusted_networks:
          - 192.168.2.0/24
        allow_bypass_login: true

default_config:

http:
  base_url: "{{ home_assistant_address }}"
  use_x_forwarded_for: True
  trusted_proxies:
    - 172.18.0.0/16

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  broker: "{{ mqtt_name }}"

light:
  - platform: mqtt
    name: "salon"
    command_topic: "pokoj/enabled"
    state_topic: "pokoj/enabled"
    payload_on: "1"
    payload_off: "0"
    xy_command_topic: "pokoj/effects/light/xy"
    xy_state_topic: "pokoj/effects/light/xy"
    brightness_command_topic: "pokoj/effects/light/brightness"
    brightness_state_topic: "pokoj/effects/light/brightness"
    white_value_command_topic: "pokoj/effects/light/whiteness"
    white_value_state_topic: "pokoj/effects/light/whiteness"
    effect_command_topic: "pokoj/effect"
    effect_state_topic: "pokoj/effect"
    effect_list: ["light", "flame", "plasma"]
    retain: True

binary_sensor:
  - platform: workday
    country: PL

automation:
  - alias: Wake up light
    trigger:
        platform: time
        at: '06:20:00'
    condition:
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
      - condition: template
        value_template: {%raw%}'{{ state_attr("sun.sun", "elevation") < 6 }}'{%endraw%} 
    action:
      - service: light.turn_on
        data:
            entity_id: light.salon
            xy_color: [0.31, 0.33]
            brightness: 255
            white_value: 255
            effect: light
  - alias: End wake up light
    trigger:
        platform: time
        at: '07:10:00'
    condition:
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
    action:
      - service: light.turn_off
        data:
            entity_id: light.salon
            